
####################################################################
# Setup hostname
####################################################################
- name: Set hostname
  hostname:
    name: '{{ hostname }}'

- name: add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1[ \t]+localhost'
    line: '127.0.1.1 {{ hostname }}'
    state: present

####################################################################
# Update APT Cache
####################################################################
- name: Update APT cache 
  apt:
    update_cache: yes

####################################################################
# Update All packages
####################################################################
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest